//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideshowDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlideServerDbEntities : DbContext
    {
           //: base("name=DefaultConnection")
        public SlideServerDbEntities()
            : base("SlideServerDbEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<Slideshow> Slideshows { get; set; }
        public virtual DbSet<SlideshowSlide> SlideshowSlides { get; set; }
        public virtual DbSet<SlideshowSoundtrack> SlideshowSoundtracks { get; set; }
        public virtual DbSet<Soundtrack> Soundtracks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSlideshow> UserSlideshows { get; set; }
    }
}
