//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideshowDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int slide_id { get; set; }
        public string slide_name { get; set; }
        public string slide_code { get; set; }
        public Nullable<System.DateTime> taken_date { get; set; }
        public string caption { get; set; }
        public Nullable<decimal> slide_height { get; set; }
        public Nullable<decimal> slide_width { get; set; }
        public Nullable<decimal> slide_margin { get; set; }
        public string image_uri { get; set; }
    }
}
