//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideshowDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slideshow
    {
        public int slideshow_id { get; set; }
        public string slideshow_title { get; set; }
        public string producer { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
