//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideshowDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideshowSoundtrack
    {
        public int slideshow_id { get; set; }
        public int soundtrack_id { get; set; }
    }
}
