//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideshowDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soundtrack
    {
        public int soundtrack_id { get; set; }
        public string song { get; set; }
        public string musician { get; set; }
        public string file_path { get; set; }
        public string file_type { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<decimal> duration { get; set; }
        public string album_cover { get; set; }
    }
}
